### ISSUE TITLE
can not use in 3.1

### ISSUE THREAD

**Issue by BUGProtectionAssociation** [RedHaloStudio/Blender-Chinese-Input#1]
never update anymore?

**Comment by RedHaloStudio** [comment]
Update it

**Comment by BUGProtectionAssociation** [comment]
> Update it

 @RedHaloStudio

> 



> 更新它


Thank you, it's helpful
谢谢你，这很有帮助
謝謝你，這很有用
ありがとう、それは役に立ちました
Merci, c’est utile
